- .travis.yml
> Add Travis configured.

- .travis.yml
- README.md
> Test Travis CI with yaml cleaned

- .travis.yml
- README.md
Remove auth configuration from connector configuration and update Ballerina version in travis configuration.
> Update README.md and travis.yml for changes

- Ballerina.lock
- Ballerina.toml
- src/amazonsqs/Module.md
- src/amazonsqs/tests/main_test.bal
Make changes for feedback given by Pramodya
> Corrected Module.md and version bumped.

- .travis.yml
- Ballerina.lock
- Ballerina.toml
- README.md
- src/amazonsqs/Module.md
> Migrate the AmazonSQS Connector from Ballerina version 1.0.1 to 1.1.0.
> Migrate the Ballerina version to 1.1.0

- .travis.yml
- Ballerina.lock
- Ballerina.toml
- README.md
- src/aws.sqs/Module.md
- src/aws.sqs/amazonsqs_connector.bal
- src/aws.sqs/amazonsqs_data_mappings.bal
- src/aws.sqs/amazonsqs_errors.bal
- src/aws.sqs/amazonsqs_utils.bal
Migrate the connector to new Ballerina version, "Swan Lake". Fixes https://github.com/ballerina-platform/module-ballerinax-aws.sqs/issues/15 .
> Migrate to Ballerina Swan Lake

- Ballerina.lock
Change the Ballerina version in lock file correctly.
> Add ballerina version change to lock file

- .github/workflows/release.yml
> To build bala file and push to ballerina central.
> Add change in release config in github workflow

- .github/workflows/ci.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- Ballerina.toml
- Module.md
- README.md
- data_mappings.bal
- endpoint.bal
- samples/manage_SQS_Standard_Queue.bal
- samples/manange_SQS_FIFO_Queue.bal
- tests/test.bal
> Adding documentation comments which are more meaningful and fix delete response return type
Fixes wso2-enterprise/choreo#4473
Fixes wso2-enterprise/choreo#4664
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> Ballerina Swan Lake Alpha5, JDK 11
> Add display annotations and http:Response fix

- endpoint.bal
> Update document comments
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> Ballerina Swan Lake Alpha5, JDK 11
> Remove optional from doc comments 

- Ballerina.toml
- endpoint.bal
> The display annotations for Azure Cosmos DB connector is inconsistent
> $Subject
> [SL Alpha 5] Make display annotations consistent

- sqs/endpoint.bal
> The display annotations for Azure Cosmos DB connector is inconsistent
> $Subject
> Make display annotations consistent 

- gradle.properties
- sqs/Dependencies.toml
Bump dependency versions to slbeta2
> Bump dependency versions for Ballerina SLBeta2

- README.md
- gradle.properties
- sqs/Dependencies.toml
- sqs/Module.md
- sqs/Package.md
- sqs/endpoint.bal
- sqs/utils.bal
> $subject
> Resolves wso2-enterprise/choreo#6666
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> JDK 11, Ballerina Swan Lake Beta2
> Update documentations to new format

- gradle.properties
- sqs/Dependencies.toml
$title
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
JDK 11
Ballerina SLBeta3
> Bump standard lib versions for Ballerina SLBeta3

- sqs/Ballerina.toml
Update keyword `dev tools` -> `it operations` in Ballerina.toml
> Update keyword `dev tools` -> `it operations`

- .github/workflows/ci.yml
- .github/workflows/daily-build.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- README.md
- sqs/Dependencies.toml
Related https://github.com/ballerina-platform/ballerina-extended-library/issues/128
One line release note: 
- Add slbeta4 migration changes
**Test Configuration**:
* Ballerina Version: Ballerina swan lake beta 4
* Operating System: Ubuntu (Linux)
* Java SDK: Java 11
> add beta4 migration changes

- README.md
- gradle.properties
- sqs/Ballerina.toml
- sqs/Dependencies.toml
- sqs/Package.md
- Bump version to `2.1.0`
- Update Ballerina version to `SLBeta6` in Package.md 
- Regenerate Dependencies.toml with `SLBeta6`
- Add `distribution = "slbeta6"` in Ballerina.toml
> Prepare for 2.1.0 release with SLBeta6

- sqs/Dependencies.toml
- Update Dependencies.toml with latest standard library versions
> Re-generate Dependencies.toml with latest pack

- gradle.properties
- sqs/Ballerina.toml
- sqs/Dependencies.toml
- sqs/Package.md
- Bump version to `2.2.0`
- Update Ballerina version to `2201.0.0` in Package.md 
- Regenerate Dependencies.toml with `2201.0.0`
- Add `distribution = "2201.0.0"` in Ballerina.toml
> Prepapre for 2.2.0 release with 2201.0.0

- .github/workflows/ci.yml
- .github/workflows/daily-build.yml
Add code lines coverage
Fixes 
https://github.com/ballerina-platform/ballerina-extended-library/issues/407
> Add code lines coverage

- .github/workflows/dev-stg-release.yml
- Use ballerina action version 2201.0.3
> Use ballerina action version 2201.0.3

- .github/workflows/release.yml
- Use 2201.0.3 in prod-release workflow
> Use Ballerina SL 2201.0.3 in release workflow

- .github/workflows/dev-stg-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- Ballerina.toml
- Dependencies.toml
- Package.md
- utils.bal
- Fix https://github.com/ballerina-platform/ballerina-extended-library/issues/462
> Fix breaking changes with SL 2201.1.1

- Ballerina.toml
- Dependencies.toml
- Package.md
- config-types.bal
- data_mappings.bal
- endpoint.bal
* Update ConnectionConfig record
* Bump connector version and ballerina version in Ballerina.toml
* Bump ballerina version in Package.md
* Update Dependencies.toml with Ballerina 2201.2.0
> Update ConnectionConfig record

- config-types.bal
> Add display annotation to Connection Configuration record
> Add display annotation to ConnectionConfig

- config-types.bal
- endpoint.bal
- Use HTTP 1.1
- Make proxy as nillable in ClientHttp1Settings
> Use HTTP 1.1 and Make proxy as nillable in ClientHttp1Settings

- Package.md
- README.md
$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/474
> Update Slack channel occurrences with Discord

- Ballerina.toml
- Dependencies.toml
- Package.md
$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/475
> Update to Ballerina version 2201.3.0

- .github/workflows/dev-stg-release.yml
- Update bal version as 2201.4.1 in dev-staging release workflow
> [2201.4.1] Update bal version as 2201.4.1

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- ballerina/tests/test.bal
- ballerina/tests/test_init.bal
- ballerina/tests/test_listener.bal
- build-config/resources/Ballerina.toml
- gradle.properties
- native/src/main/java/io/ballerina/lib/aws/sqs/listener/Listener.java
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Related Pull Requests (remove if not relevant)
- Pull request 1
- Pull request 2
One line release note: 
- One line describing the feature/improvement/fix made by this PR 
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Ballerina Version:
* Operating System:
* Java SDK:
> Add suggestions from code review

- ballerina/Dependencies.toml
- ballerina/tests/test.bal
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Related Pull Requests (remove if not relevant)
- Pull request 1
- Pull request 2
One line release note: 
- One line describing the feature/improvement/fix made by this PR 
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Ballerina Version:
* Operating System:
* Java SDK:
> Add logs to debug the failing test

- ballerina/Dependencies.toml
- ballerina/tests/test.bal
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Related Pull Requests (remove if not relevant)
- Pull request 1
- Pull request 2
One line release note: 
- One line describing the feature/improvement/fix made by this PR 
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Ballerina Version:
* Operating System:
* Java SDK:
> Refactor test 

- README.md
- ballerina/README.md
- examples/README.md
> Update URls in README files

- ballerina/Dependencies.toml
- ballerina/tests/test.bal
> Refactor testDeleteMessageBatchSuccess test
